spring:
  application:
    name: DrChaYong
  profiles:
#    active:
#      - local
#    group:
#      local:
#        - db-local
#        - eureka-local
#      prod:
#        - db-prod
#        - eureka-prod
    include:
      - private

server:
  port: 8080